---

- name: create deploy group
  group:
    name: "{{ deploy_group }}"
    state: present

- name: create deploy user
  user:
    name: "{{ deploy_user }}"
    group: "{{ deploy_group }}"

- name: add ssh key for user
  authorized_key:
    user: "{{ deploy_user }}"
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
