---

- name: install phantomjs
  apt:
    pkg: phantomjs
    state: present
    update_cache: yes
  sudo: yes

- name: create phantomjs group
  group:
    name: "{{ phantomjs_group }}"
    state: present
  sudo: yes

- name: create phantomjs user
  user:
    name: "{{ phantomjs_user }}"
    group: "{{ phantomjs_group }}"
  sudo: yes

- name: setup phantomjs init script
  template:
    src: phantom.conf.j2
    dest: /etc/init/phantom.conf
  sudo: yes

- name: start phantomjs on boot
  service:
    name: phantom
    enabled: yes
    state: restarted
  sudo: yes
