---
# This playbook deploys the whole application stack in this site.

- name: install system dependencies
  hosts: vagrant
  remote_user: vagrant
  sudo: yes

  roles:
    - mongodb

- name: create deploy user
  hosts: vagrant
  remote_user: vagrant
  sudo: yes

  roles:
    - usersetup

- name: deploy app
  hosts: vagrant
  remote_user: vagrant

  roles:
    - app
